import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { completeWithOverseasStrategy } from '../gmail-provider-router.mjs';

const root = resolve(process.cwd(), 'data', 'news');
const cacheFile = resolve(root, 'congress.json');
const terms = /crypto|cryptocurrency|digital asset|stablecoin|blockchain|bitcoin|ethereum|virtual currency|token/i;
const readCache = async () => { try { return JSON.parse(await readFile(cacheFile, 'utf8')); } catch { return {}; } };
const saveCache = async (cache) => { await mkdir(root, { recursive: true }); await writeFile(cacheFile, JSON.stringify(cache, null, 2), { mode: 0o600 }); };
async function fetchBills() { const key = String(process.env.CONGRESS_API_KEY || '').trim(); if (!key) return []; const response = await fetch(`https://api.congress.gov/v3/bill?format=json&limit=50&api_key=${encodeURIComponent(key)}`, { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(15_000) }); if (!response.ok) throw new Error(`Congress API returned ${response.status}`); return (await response.json()).bills || []; }
async function score(item) { const raw = await completeWithOverseasStrategy({ content: `只返回0到100的整数，评估这条美国国会法案对比特币、以太坊和整体加密市场的重要性。0-29无关，30-59一般金融立法，60-74有行业关联但影响有限，75-89明显影响数字资产或稳定币行业，90-94重大监管法案，95-100通过或推动国家级数字资产制度。标题：${item.title}\n摘要：${item.excerpt}`, model: process.env.CONGRESS_RELEVANCE_MODEL || 'gpt-5.6-luna' }); const value = Number(String(raw).match(/\b(?:100|[1-9]?\d)\b/)?.[0]); if (!Number.isInteger(value) || value < 0 || value > 100) throw new Error('Invalid Congress relevance score.'); return value; }
export async function collectCongress({ onRelevant } = {}) { const cache = await readCache(); let discovered = 0; let relevant = 0; let bills; try { bills = await fetchBills(); } catch (error) { console.warn('Congress API unavailable', error.message); return { discovered, relevant, cached: Object.keys(cache).length }; } for (const bill of bills.filter((item) => terms.test(`${item.title || ''} ${item.latestAction?.text || ''}`)).slice(0, 20)) { const id = String(bill.url || bill.billNumber || `${bill.congress}-${bill.type}-${bill.number}`); if (cache[id] && !cache[id].error) continue; discovered += 1; try { const title = String(bill.title || bill.number || 'Congress bill'); const item = { id, source: 'Congress.gov', sourceUrl: bill.url || `https://www.congress.gov/bill/${bill.congress}th-congress/${String(bill.type || '').toLowerCase()}/${bill.number}`, title, content: String(bill.latestAction?.text || ''), excerpt: String(bill.latestAction?.text || title).slice(0, 2_500), publishedAt: Date.parse(bill.updateDate || bill.latestAction?.actionDate) || Date.now(), collectedAt: Date.now(), impactScore: await score({ title, excerpt: String(bill.latestAction?.text || title).slice(0, 2_500) }) }; cache[id] = item; await saveCache(cache); if (item.impactScore >= 75 && onRelevant) { relevant += 1; await onRelevant(item); } } catch (error) { cache[id] = { id, source: 'Congress.gov', error: error.message, collectedAt: Date.now() }; await saveCache(cache); } } return { discovered, relevant, cached: Object.keys(cache).length }; }
